21.4.0 branch
strusoft/femdesign-api pull request #489
Opened 2022-09-05 09:40 UTC by andosca

2022-09-22 16:02 UTC, xRadne requested changes

2022-09-23 11:17 UTC, xRadne commented on FemDesign.Core/Geometry/Point3d.cs
> +        public static Point3d operator /(double number, Point3d p1) => new Point3d(p1.X / number, p1.Y / number, p1.Z / number);
@Marco-Pellegrino I don't think `5 / p` makes any sense. I think we should remove this. 

`p / 5` is a shorter way to scale the coordinate and make it 5 times closer to the origin.

2022-09-23 11:17 UTC, xRadne commented on FemDesign.Core/Geometry/LineEdge.cs
> +        public Point3d StartPoint => base.Points[0];
I like this!

2022-09-23 11:22 UTC, xRadne requested changes

2022-09-23 11:22 UTC, xRadne commented on FemDesign.Core/Geometry/Edge.cs
> +            this.Normal = localY ?? (endPoint - startPoint).Cross(Vector3d.UnitZ);
Have this been tested? 

I think it should be `-(endPoint - startPoint).Cross(Vector3d.UnitZ)` (-) to follow the "right hand rule".

And I think this will throw an error if the edge is vertical (paralell to UnitZ)

2022-09-23 11:36 UTC, Marco-Pellegrino commented on FemDesign.Core/Geometry/Point3d.cs
> +        public static Point3d operator /(double number, Point3d p1) => new Point3d(p1.X / number, p1.Y / number, p1.Z / number);
Thanks @xRadne 
I have done a copy and paste following the *operator.
I'll fix it as it does make too much sense to do number / point

2022-09-23 11:40 UTC, Marco-Pellegrino commented on FemDesign.Core/Geometry/Edge.cs
> +            this.Normal = localY ?? (endPoint - startPoint).Cross(Vector3d.UnitZ);
Minus sign in front is probably better but it does work also as it is.

I'll update the logic for a vertical edge because, as you said, it would create an error.

2022-09-23 11:50 UTC, xRadne commented on FemDesign.Core/Geometry/Edge.cs
> +            this.Normal = localY ?? (endPoint - startPoint).Cross(Vector3d.UnitZ);
Bar sections will be upside down otherwise :)

2022-09-23 13:30 UTC, Marco-Pellegrino reviewed
I should have done the changes

2022-09-28 15:24 UTC, Marco-Pellegrino commented
One error and some warnings appear when we serialise and open a model though the API. FEM-Design can still open the file though.

![image](https://user-images.githubusercontent.com/53620289/192819199-31fc12ad-86ad-4a3e-ba12-af42e5d49892.png)

2022-09-30 09:57 UTC, merged

2022-09-30 14:00 UTC, Marco-Pellegrino commented
@xRadne 

| Test | Result |
| :---         |     :---:      |
| FemDesign.Tests| OK |
| C# Example | OK |
| Gh Global Tests Analysis| OK |
| Gh Global Tests Deconstruct| OK |
| Gh Global Tests ReadWrite| OK |

File on my Local Machine have been used to test each issue.

Let me know if there is something that I have missed.